# Default configuration for a HTML site

# Site title and author
title: Moose Research Initiative — Theme 4
author: Leonard Hambrecht

# Site URL
url: https://hambrecht.github.io/drones4wildlifesurveys/

# Description of the site
description: Examining the current practicality and potential of Copter and Fixed Wing Remotely Piloted Airborne Systems for wildlife surveys, with comparisons of currently employed survey methods

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional settings
show_excerpts: true

# List of pages to include on the navigation bar
nav:
  - title: Home
    url: /
  - title: Simulations
    url: /sim.md
  - title: Deep learning
    url: /dl/
  - title: Field work
    url: /fieldwork.html
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Path to the directory containing the site's content
content_dir: _posts

# Path to the directory containing the site's static files (e.g. images, CSS)
static_dir: assets

# Path to the template file used for generating HTML pages
layout: default.html
