# Default configuration for a HTML site

# Site title and author
title: My HTML Site
author: John Doe

# Site URL
url: http://example.com

# Description of the site
description: This is an example HTML site.

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional settings
show_excerpts: true

# List of pages to include on the navigation bar
nav:
  - title: Home
    url: /
  - title: Simulations
    url: /sim/
  - title: Deep learning
    url: /dl/
  - title: Field work
    url: /fieldwork
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Path to the directory containing the site's content
content_dir: _posts

# Path to the directory containing the site's static files (e.g. images, CSS)
static_dir: assets

# Path to the template file used for generating HTML pages
layout: default.html
