---
title: "Interactive Map Example"
output: html_document
---
| [Home](index.md) | [Simulations](sim.html) | [Deep Learning](dl.md) | [Field Work](fieldwork.html) | [IRSS](https://irsslab.forestry.ubc.ca/) | [fRI Research](https://friresearch.ca/) | [Contact](mailto:137965368+hambrecht@users.noreply.github.com) |

# Thunderbay

## My Interactive Map

```{r include=FALSE}
library(here)
library(leaflet)
library(sf)
library(terra)
library(dplyr)
studyArea <- st_read("mapLayers/studyAreaOntario.shp")
studyArea <- st_transform(studyArea, crs = 4326) # WGS84
strata <- st_read("mapLayers/strata.shp")
strata <- st_transform(strata, crs = 4326) # WGS84
strata$name <- c("East", "1 Day", "West")
aerodrome <- st_read("mapLayers/aerodrome.shp")
aerodrome <- st_transform(aerodrome, crs = 4326) # WGS84


# Define a color palette based on the 'name' column
pal <- colorFactor(palette = "Set2", domain = strata$name)
```
```{r, include=FALSE}
print(studyArea)
```
```{r leaflet-map, echo=FALSE}
leaflet() %>%
  addTiles() %>%
  addTiles(
    "https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png",
    layerId = "_e5657323_f251_4d70_9366_f5879b155d3e",
    group = "Terrain",
    options = WMSTileOptions()
  ) %>%
  addTiles(
    "https://tile.opentopomap.org/{z}/{x}/{y}.png",
    layerId = "_14b46c75_d6e7_481f_b57d_a0bbb927294a",
    group = "Topo",
    options = WMSTileOptions()
  ) %>%
  addPolygons(
    data = studyArea,
    color = "red",
    weight = 3,
    opacity = 1,
    fillOpacity = 0,
    group = "Study Area"
  ) %>%
  addLegend("bottomleft", col = "red", label = "Study Area", title = "Study area") %>%
  addPolygons(
    data = strata,
    color = ~ pal(name),
    weight = 1,
    opacity = 1,
    fillOpacity = 0.4,
    popup = ~name,
    group = "Strata"
  ) %>%
  addLegend(
    "bottomleft",
    pal = pal, values = strata$name, title = "Strata"
  ) %>%
  addPolygons(
    data = aerodrome,
    color = "yellow",
    weight = 1,
    opacity = 1,
    fillOpacity = 0.4,
    popup = "AeroDrome: Two Island Lake",
    group = "Aerodrome"
  ) %>%
  addLayersControl(
    overlayGroups = c("Study Area", "Strata", "Aerodrome", "Terrain", "Topo"),
    options = layersControlOptions(collapsed = FALSE)
  ) %>%
  hideGroup(c("Terrain", "Topo"))
```